name: Aerate
favicon: null
layout_spectrum: 0.9940998712554574
typography_spectrum: 0.500734027242288
title: Breathe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4757432737387717
  lightness: 0.3626234605908394
  saturation: 0.8526915349066257
  rhythmicContrast: 0.09770686295814812
purpose: []
