name: Aerate
favicon: null
layout_spectrum: 0.9940998712554574
typography_spectrum: 0.49601
title: Breathe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#06091a'
    - '#040496'
    - '#82b8de'
    - '#4157e1'
    - '#508be7'
  brandStrength: 1
  lightness: 0.3626234605908394
  saturation: 0.8526915349066257
  rhythmicContrast: 0.5
purpose: []
